name: Bug report
description: Something is broken or inconsistent.
title: "[Bug]: "
labels: ["type:bug"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - API
        - Data
        - Web
        - Docs/Infra
    validations:
      required: true

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Describe the issue clearly.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Logs, screenshots, payloads, patch id, etc.
    validations:
      required: false
