name: Feature request
description: Propose a player-centric improvement.
title: "[Feature]: "
labels: ["type:feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Player problem
      description: What player pain does this solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should we build/change?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - API
        - Data
        - Web
        - Docs/Infra
    validations:
      required: true
